all:
  children:
    production:
      hosts:
        aws_ec2:
          ansible_host: "{{ lookup('env', 'SSH_HOST') }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3
